### ISSUE TITLE
The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

### ISSUE THREAD

**Issue by ifredom** [fluttercandies/extended_image_library#14]
When I upgrade `flutter upgrade`, I can't start it`flutter run`

![image](https://user-images.githubusercontent.com/13759936/69604826-7cca7c00-1059-11ea-89ff-4ed1c5bc153c.png)

![image](https://user-images.githubusercontent.com/13759936/69604852-910e7900-1059-11ea-8023-17a33cf6d999.png)

**Comment by zmtzawqlp** [comment]
see pinned issue
