### ISSUE TITLE
[Feature Request] Get cache image file optional parameter

### ISSUE THREAD

**Issue by itssidhere** [fluttercandies/extended_image_library#23]
Currently, the **getCachedImageFile** method returns the cached file and null if there is no file with the given URL in the cache. We should also have an optional parameter to get the image from the URL and cache it if it's not present in the cache or a separate method for it.

**Comment by zmtzawqlp** [comment]
getNetworkImageData  is what you want

**Comment by itssidhere** [comment]
I am actually looking for a method which returns a file after caching if it is not present in the cache or just returns the file from the cache. getNetworkImageData doesn't return a file and what my point is that the same method getCachedImageFile should have an optional parameter **fromNetwork** to allow saving the file in the cache if it's not already present.

**Comment by zmtzawqlp** [comment]
In fact，the method is easy to create, It doesn't seem to make much sense to make one more method.

``` dart
await getNetworkImageData(url);
final String key = keyToMd5(url);
final Directory cacheImagesDirectory = Directory(
 join((await getTemporaryDirectory()).path, cacheImageFolderName));
final File cacheFlie = File(join(cacheImagesDirectory.path, key));
return cacheFlie;
```

**Comment by itssidhere** [comment]
Alright, I will check with this workaround. Don't you think that having this method as putIfAbsent optional parameter in getCachedImageFile will be more intuitive?

**Comment by itssidhere** [comment]
Correct me if I am wrong isn't doing this is same as you did?

   ```
 await getNetworkImageData(url, useCache: true);
    final File cacheFlie = (await getCachedImageFile(url));
    return cacheFlie;
```

**Comment by zmtzawqlp** [comment]
``` dart
var data= await getNetworkImageData(url);
if(data!=null)
{
final String key = keyToMd5(url);
final Directory cacheImagesDirectory = Directory(
 join((await getTemporaryDirectory()).path, cacheImageFolderName));
final File cacheFlie = File(join(cacheImagesDirectory.path, key));
return cacheFlie;
}
``` 
may be your network image will download fail. and you don't need to traversing the folder if you make sure the file is exist.

**Comment by itssidhere** [comment]
Thanks. I have one more question I would like to ask later.
