### ISSUE TITLE
Cache duration setting

### ISSUE THREAD

**Issue by pulstar** [fluttercandies/extended_image_library#31]
This widget could have a cache duration setting like that:

`cacheDuration: Duration(days: 7)`

After this time the cache is expired and the image is reloaded.

Also the image editor could have a vertical flip option.

**Comment by zmtzawqlp** [comment]
please open another issue about Also the image editor could have a vertical flip option under extended_image

**Comment by zmtzawqlp** [comment]
close with https://github.com/fluttercandies/extended_image_library/commit/f05275bb812102f960bbfbefb5a0b4d831795b8c
