### ISSUE TITLE
Vertical Flip in image editor

### ISSUE THREAD

**Issue by pulstar** [fluttercandies/extended_image_library#32]
The image editor could have also a vertical flip option.

**Comment by zmtzawqlp** [comment]
i didn't get you

**Comment by pulstar** [comment]
The image editor have an horizontal flip, but not a vertical flip option. Horizontal flip mirror the image from left to right and the vertical flip mirror from up to bottom.

**Comment by zmtzawqlp** [comment]
create issue in right package

**Comment by pulstar** [comment]
Which is the right package? This is not an issue, but a feature.

**Comment by zmtzawqlp** [comment]
i didn't see any reference to https://github.com/fluttercandies/extended_image_library

**Comment by pulstar** [comment]
Here is the extended_image git, isn

**Comment by pulstar** [comment]
Here is the extended_image git, isn't it?
