### ISSUE TITLE
长列表中

### ISSUE THREAD

**Issue by allpepo** [fluttercandies/extended_image_library#34]
长列表中(SliverChildBuilderDelegate返回列表卡片)，快速滚动为出现之前加载好的图片再次loading加载显示。  Flutter自带的Image.network()不会出现这样。 
请问是什么原理导致这个逻辑呢。  
谢谢回答。

**Comment by zmtzawqlp** [comment]
try set this https://github.com/fluttercandies/extended_image/blob/a26bc779e88aab65c79e31c250ddbe236c0b7b8e/lib/src/extended_image.dart#L747
