### ISSUE TITLE
flutter build web not working due to File type

### ISSUE THREAD

**Issue by tc** [fluttercandies/extended_image_library#36]
Does extended_image_library support flutter web?

I'm seeing this error on ``flutter build web``, ios and android work fine.

```
Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:extended_image_library/src/_platform_web.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.0/lib/src/_platform_web.dart').
                                            ExtendedImage.file(selfie!),
```

**Comment by zmtzawqlp** [comment]
File is from dart io，it's not for web，you should take care of it.

**Comment by tc** [comment]
@zmtzawqlp can you clarify how to take care of it?

I'm using ExtendedImage.file to display an uploaded image.

Should I check `Platform.isWeb` and not show this image?

**Comment by zmtzawqlp** [comment]
you can find what api can't use in web on https://stackoverflow.com.  ios and android are not the same as web

**Comment by tc** [comment]
Thanks @zmtzawqlp.

I used the "ExtendedImage.file()" API and looked up "is ExtendedImage.file usable on flutter web?" but got 0 results.

Is there a suggested alternative API to use for flutter web vs mobile APIs?

**Comment by zmtzawqlp** [comment]
web flie=>byte array=> ExtendedImage.memory
