### ISSUE TITLE
`clearMemoryCacheWhenDispose` is not working with `imageCacheName` property set

### ISSUE THREAD

**Issue by givip** [fluttercandies/extended_image_library#44]
extended_image version 6.3.2

Following configuration doesn't work as intended:

```
ExtendedImage.network(
    url,
    imageCacheName: 'custom_image_cache_name',
    clearMemoryCacheWhenDispose: true,
)
```

The reason is that method `obtainCacheStatus` is not overrided in `Extended*ImageProvider` classes.

Default `obtainCacheStatus` implementation always checks status for default `ImageCache` in `PaintingBinding.instance.imageCache`

**Comment by zmtzawqlp** [comment]
please update [extended_image_library](https://github.com/fluttercandies/extended_image_library) to 3.4.1
