### ISSUE TITLE
[Feature request][Flutter 3.10.0] - Use loadImage instead of loadBuffer

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_image_library#52]
### Platforms

dart

### Description

Instead of implementing loadBuffer use loadImage.

### Why

loadBuffer was deprecated here:
https://github.com/flutter/flutter/pull/118966

and just now released to stable.

**Comment by zmtzawqlp** [comment]
<img width="550" alt="截屏2023-05-12 09 37 59" src="https://github.com/fluttercandies/extended_image_library/assets/16477333/3b1ca07a-3878-42d5-a5f2-1388597a03b4">


i can't build successful after change to loadImage, `ImageDecoderCallback` has the same name

**Comment by naamapps** [comment]
Not sure I understand..
For me it's different.
Are you on flutter 3.10.0?
<img width="942" alt="image" src="https://github.com/fluttercandies/extended_image_library/assets/37176893/b59fb4f5-0b4d-4982-90b5-e739453350f6">

**Comment by naamapps** [comment]
Hey @zmtzawqlp, do you have updates on this?

**Comment by zmtzawqlp** [comment]
3.5.0 is ready.

**Comment by naamapps** [comment]
Thank you!
