### ISSUE TITLE
[Feature request] Update package Web dependency to 0.5

### ISSUE THREAD

**Issue by yuhangang** [fluttercandies/extended_image_library#62]
### Platforms

dart

### Description

I get dependency conflict when trying to update other packages which depends on web v0.5.0 (currently this package uses v0.4.0). Hope you can consider to update the package web version to v0.5.0.

**Comment by zmtzawqlp** [comment]
use dependency_overrides ，
environment:
sdk: '>=2.19.0 <4.0.0'
flutter: '>=3.16.0'

maybe your package need 0.5 but in 3.16.0, web is 0.4, we need to keep more version to fit
