### ISSUE TITLE
[Feature request] Update JS deps to match js: >=0.6.7 <0.8.0

### ISSUE THREAD

**Issue by TatsuUkraine** [fluttercandies/extended_image_library#65]
### Platforms

dart

### Description

Update deps to match deps resolution in recent stable flutter release

`test` package: https://github.com/dart-lang/test/blob/master/pkgs/test/pubspec.yaml#L18
`build_runner` package: https://github.com/dart-lang/build/blob/master/build_runner/pubspec.yaml#L32

**Comment by AlexV525** [comment]
c330c9f138be4409dc1b8cb8b74165e1b43bab9d

**Comment by TatsuUkraine** [comment]
Thanks!
