### ISSUE TITLE
图片闪烁

### ISSUE THREAD

**Issue by zp-techie** [fluttercandies/extended_image_library#67]
### Version

1.10.16

### Platforms

Android

### Device Model

小米

### flutter info

```sh
在类似微信的九宫格选图中，删除一个图片   ，其他的图都会闪烁，使用image.asset不会闪烁。下面这个属性不论配置false或者true都不能解决
gaplessPlayback
```

### How to reproduce?

在类似微信的九宫格选图中，删除一个图片   ，其他的图都会闪烁，使用image.asset不会闪烁。下面这个属性不论配置false或者true都不能解决
gaplessPlayback

**Comment by zmtzawqlp** [comment]
有没有可以运行的最小demo，能重现你的问题的，麻烦提供一下

**Comment by zp-techie** [comment]
> 长按删除或者排序的    按下去的时候就闪烁    抬起也闪烁

[v_nine_grid_test.zip](https://github.com/fluttercandies/extended_image/files/14081145/v_nine_grid_test.zip)

**Comment by zmtzawqlp** [comment]
另外请提供，你使用的flutter版本和 Extendedimage 使用的版本

**Comment by zp-techie** [comment]
> 另外请提供，你使用的flutter版本和 Extendedimage 使用的版本
flutter:3.16.8
extend:8.2.0

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/commit/33422e7f5fbc755c6ec63cf0741cabd0f71cd2cf

请更新  extended_image_library 到 4.0.4
