### ISSUE TITLE
[Feature request] Upgrade the "web" library to the latest version

### ISSUE THREAD

**Issue by anantheshadiga** [fluttercandies/extended_image_library#68]
### Platforms

Web

### Description

The current version of the extended_image_library package depends on an outdated version of the web package. This dependency on an older version of web creates compatibility issues when trying to integrate extended_image_library with other packages that rely on a more up-to-date version of web. As a result, developers face difficulties in maintaining a consistent and modern development environment, which may lead to conflicts, deprecated functionalities, or even the inability to use certain features provided by newer versions of web.

Please consider updating the web package dependency to the latest stable version. This will ensure compatibility with other packages and help maintain a seamless and modern development experience for all users of extended_image_library.

### Why

The primary reason for requesting this feature is to ensure compatibility and smooth integration with other packages that depend on the latest version of the web package. In many projects, developers use multiple packages, and when one package relies on an outdated version of a dependency, it can cause conflicts or prevent the use of newer, improved features available in the updated versions.

**Comment by tannker** [comment]
Yes, we have also other packages that have introduced dependences on web ^1.0.0. As  extended_image_library needs to have web 0.6.0, it blocks us various important upgrades. Hence is it possible to upgrade web dependency  to web ^1.0.0

**Comment by zmtzawqlp** [comment]
the same as https://github.com/fluttercandies/extended_image_library/issues/62

**Comment by tannker** [comment]
@zmtzawqlp i have both extended_image_library and extended_image on their latest version, but I still get error that web 1.0 is not supported by them. What do you advise on this?

**Comment by zmtzawqlp** [comment]
dependency_overrides:
  web: ^1.0.0

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/commit/77073a70aa6797c33dd2df6bf1ccef42496881cd

done
